version: "3.9"

services:
   mongo:
    container_name: twitter-db
    image: mongo:6.0.5
    restart: always
    environment:
      - MONGO_INITBD_DATABASE=twitter_local
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - v-twitter-db:/data/db
    ports:
      - "27164:27017"


volumes:
  v-twitter-db: